[package]
edition = "2024"
name = "Application"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
hotline = {path = "../../hotline"}
notify = "8.0"
sdl2 = {version = "0.37.0", features = ["ttf", "image"]}
xxhash-rust = { version = "0.8", features = ["xxh3"] }
png = "0.17"