[package]
name = "CpuTextRenderer"
version = "0.1.0"
edition = "2021"

[dependencies]
hotline = { path = "../../hotline" }
png = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]