[package]
edition = "2024"
name = "hotline"
version = "0.1.0"

[dependencies]
hotline-macros = {path = "../hotline-macros"}
libloading = "0.8"
libc = "0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
